# Generated by Django 5.2.6 on 2025-09-20 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Банківська карта'), ('bank_transfer', 'Банківський переказ'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Не вдалося'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID транзакції')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Відповідь шлюзу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Банківська карта'), ('bank_transfer', 'Банківський переказ'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], max_length=20, verbose_name='Тип способу оплати')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=200, verbose_name='ID способу оплати Stripe')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, verbose_name='ID клієнта Stripe')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Метадані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Спосіб оплати',
                'verbose_name_plural': 'Способи оплати',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума повернення')),
                ('reason', models.TextField(verbose_name='Причина повернення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Не вдалося'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID транзакції')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Відповідь шлюзу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Платіж')),
            ],
            options={
                'verbose_name': 'Повернення',
                'verbose_name_plural': 'Повернення',
                'ordering': ['-created_at'],
            },
        ),
    ]
