version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ptashka_postgres
    environment:
      POSTGRES_DB: ptashka_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ptashka_network

  redis:
    image: redis:7-alpine
    container_name: ptashka_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ptashka_network

  web:
    build: .
    container_name: ptashka_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=ptashka_shop
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - ptashka_network

  celery:
    build: .
    container_name: ptashka_celery
    command: celery -A ptashka_shop worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=ptashka_shop
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - ptashka_network

  celery-beat:
    build: .
    container_name: ptashka_celery_beat
    command: celery -A ptashka_shop beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=ptashka_shop
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - ptashka_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  ptashka_network:
    driver: bridge
