# Generated by Django 5.2.6 on 2025-09-20 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID сесії')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Остання активність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна сесія')),
                ('context', models.JSONField(blank=True, default=dict, help_text='JSON з контекстом розмови', verbose_name='Контекст сесії')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сесія чату',
                'verbose_name_plural': 'Сесії чату',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Унікальний ідентифікатор сесії чату', max_length=100, verbose_name='ID сесії')),
                ('message_type', models.CharField(choices=[('user', 'Користувач'), ('bot', 'Бот'), ('system', 'Система')], default='user', max_length=10, verbose_name='Тип повідомлення')),
                ('content', models.TextField(verbose_name='Текст повідомлення')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='JSON з додатковою інформацією про повідомлення', verbose_name='Додаткові дані')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Повідомлення чатбота',
                'verbose_name_plural': 'Повідомлення чатбота',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='chatbot_cha_session_488328_idx'), models.Index(fields=['user', 'timestamp'], name='chatbot_cha_user_id_ac2c89_idx')],
            },
        ),
    ]
